# Generated by Django 4.2.6 on 2024-01-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_alter_scrap_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='picture',
            field=models.ImageField(upload_to='scrapimages'),
        ),
    ]
