# Generated by Django 4.2.6 on 2024-01-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_alter_scrap_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='picture',
            field=models.ImageField(null=True, upload_to='scrapimages'),
        ),
    ]
