# Generated by Django 4.2.6 on 2024-01-22 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0004_alter_scrap_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrap',
            old_name='picture',
            new_name='scrap_image',
        ),
    ]
