# Generated by Django 4.2.6 on 2024-01-22 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_rename_picture_scrap_scrap_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrap',
            old_name='scrap_image',
            new_name='picture',
        ),
    ]
