# Generated by Django 4.2.6 on 2024-01-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0006_rename_scrap_image_scrap_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='scrapimages'),
        ),
    ]
